# https://python-semantic-release.readthedocs.io/en/latest/#setting-up-version-numbering
[tool.semantic_release]
version_variable = "setup.py:__version__"
branch = "main"
upload_to_repository = false
upload_to_release = true
#repository_url = "https://github.com/ocadotechnology/codeforlife"
