# https://python-semantic-release.readthedocs.io/en/latest/#setting-up-version-numbering
[tool.semantic_release]
version_variable = "codeforlife/version.py:__version__"
branch = "main"
upload_to_repository = false
upload_to_release = true

[tool.black]
line-length = 120
extend-exclude = "^/codeforlife/migrations/"

#[tool.pytest.ini_options]
#DJANGO_SETTINGS_MODULE = "tests.settings"
#testpaths = []
#addopts = "-p no:warnings"
