name: Test

on: push

jobs:
  test:
    if: github.event.commits[0].author.name != 'semantic-release'
    name: Test Code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev

      - name: Check Code Format
        run: if ! pipenv run black --check .; then exit 1; fi

      - name: Check Migrations
        run: pipenv run python manage.py makemigrations --check --dry-run

      # TODO: assert code coverage target.
      - name: Test Code Units
        run: pipenv run pytest
